import numpy as np

pfet_mod_0 = {  "vth0_nom" : 2.08113 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 9999.92 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 1.11407e-05 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 3.41512 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 13.5087 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_1 = {  "vth0_nom" : 2.63072 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 5999.62 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 32.2943 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 15.6882 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 10.5543 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_2 = {  "vth0_nom" : 2.38937 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 5973.51 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 21.2644 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 15.7457 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 15.317 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_3 = {  "vth0_nom" : 2.08113 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 9999.92 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 1.11407e-05 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 3.41512 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 13.5087 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_4 = {  "vth0_nom" : 2.7 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 7999.69 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 15 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 24.9999 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 27.8475 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_5 = {  "vth0_nom" : 2.83706 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 0.0526208 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 0.0132645 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 0.0132645 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 28.8009,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_6 = {  "vth0_nom" : 2.54819 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 4404.24 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 24.9335 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 8.34883 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 11.0919,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_7 = {  "vth0_nom" : 3.48149 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 0.01 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 7.37549 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 16.941 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 1,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_8 = {  "vth0_nom" : 2.63399 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 4933.4 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 59.2967 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 11.6046 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 15.4893,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_9 = {  "vth0_nom" : 3.00971 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 4700.55 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 6.17252 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 11.8673 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 50 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_10 = {  "vth0_nom" : 4.84695 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 4114.3 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 4.40825 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 9.99882 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 16.6503 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
pfet_mod_11 = {  "vth0_nom" : 2.55 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 54.1708 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 24.5 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 49.0004 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 23 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 1 
}
nfet_mod_0 = {  "vth0_nom" : 1.28751 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 1.75772 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 0.967479 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 1.71788 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 32.1932 ,
                "eta0_nom" : 1.40301 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 5.33214 
}
nfet_mod_1 = {  "vth0_nom" : 1.12168 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 1.21519 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 1.38277 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 3.86037 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 35 ,
                "eta0_nom" : 4.17501 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 8.47307 
}
nfet_mod_2 = {  "vth0_nom" : 1.18565 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 1.22972 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 1.529 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 4.11137 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 7.50508 ,
                "eta0_nom" : 1.8545 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 5.77825 
}
nfet_mod_3 = {  "vth0_nom" : 1.30949 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 16.6213 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 2.36 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 6.08023 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 6.04219 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 8 
}
nfet_mod_4 = {  "vth0_nom" : 1.29339 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 0.000175058 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 2.78088 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 11.342 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 11.342 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 5 
}
nfet_mod_5 = {  "vth0_nom" : 1.32466 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 0.197719 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 0.00100201 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 7.31298 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 2.41414 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 15 
}

nfet_mod_6 = {  "vth0_nom" : 1.06358 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 0.117696 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 35.9539 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 9.30034 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 23.4256 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 14.9998 
}
nfet_mod_7 = {  "vth0_nom" : 1.25709 ,
                "dvt0_nom" : 1 ,
                "dvt1_nom" : 1 ,
                "vsat_nom" : 0.0405727 ,
                "ua_nom" : 1 ,
                "ub_nom" : 1 ,
                "uc_nom" : 1 ,
                "rdsw_nom" : 144.793 ,
                "prwg_nom" : 1 ,
                "u0_nom" : 8.58843 ,
                "rdw_nom" : 1 ,
                "rsw_nom" : 1 ,
                "nfactor_nom" : 4.30869 ,
                "eta0_nom" : 1 ,
                "dsub_nom" : 1 ,
                "pclm_nom" : 1 ,
                "pvag_nom" : 1 ,
                "delta_nom" : 9.99998 
}

model_devs = [
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__nfet_01v8_lvt l=0.15 w=1.6 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__nfet_01v8_lvt l=0.19 w=7 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__nfet_01v8_lvt l=0.25 w=1.6 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__nfet_01v8_lvt l=1 w=1.6 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__nfet_01v8_lvt l=1 w=3 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__nfet_01v8_lvt l=8 w=1.6 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__nfet_01v8_lvt l=20 w=0.64 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__nfet_01v8_lvt l=100 w=100 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__pfet_01v8_lvt l=8 w=0.84 mult=3 m=3",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__pfet_01v8_lvt l=0.35 w=1.6 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__pfet_01v8_lvt l=0.5 w=0.42 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__pfet_01v8_lvt l=0.35 w=0.55 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__pfet_01v8_lvt l=0.5 w=0.64 mult=2 m=2",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__pfet_01v8_lvt l=0.35 w=0.5 mult=3 m=3",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__pfet_01v8_lvt l=2 w=5 mult=1 m=1",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__pfet_01v8_lvt l=4 w=7 mult=3 m=3",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__pfet_01v8_lvt l=8 w=1.6 mult=3 m=3",
    "XM1 DRAIN GATE 0 0 sky130_fd_pr__pfet_01v8_lvt l=8 w=5 mult=3 m=3"
]
mods_list = {
    "pfet_mod_0": pfet_mod_0,
    "pfet_mod_1": pfet_mod_1,
    "pfet_mod_2": pfet_mod_2,
    "pfet_mod_3": pfet_mod_3,
    "pfet_mod_4": pfet_mod_4,
    "pfet_mod_5": pfet_mod_5,
    "pfet_mod_6": pfet_mod_6,
    "pfet_mod_7": pfet_mod_7,
    "pfet_mod_8": pfet_mod_8,
    "pfet_mod_9": pfet_mod_9,
    "pfet_mod_10": pfet_mod_10,
    "pfet_mod_11": pfet_mod_11,
    "nfet_mod_0": nfet_mod_0,
    "nfet_mod_1": nfet_mod_1,
    "nfet_mod_2": nfet_mod_2,
    "nfet_mod_3": nfet_mod_3,
    "nfet_mod_4": nfet_mod_4,
    "nfet_mod_5": nfet_mod_5,
    "nfet_mod_6": nfet_mod_6,
    "nfet_mod_7": nfet_mod_7
}